test

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -23,22 +23,16 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+          if [ -f "${{ github.workspace }}/package.json" ]; then
+             echo "manager=npm" >> $GITHUB_OUTPUT
+             echo "command=ci" >> $GITHUB_OUTPUT
+             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+             echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
+             exit 0
+           else
+             echo "Unable to determine package manager"
+             exit 1
+           fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
@@ -75,4 +69,4 @@ jobs:
           server: riverscape.ca
           username: ${{ secrets.ftp_username }}
           password: ${{ secrets.ftp_password }}
-          server-dir: /staging/
+          server-dir: /staging.riverscape.ca/
